#!/usr/bin/env -S ruby -w

require "open3"

def run(cmd, *args)
  system(cmd, *args) || abort("Failed running #{cmd}")
end

run "standardrb", "./src/", "./test"
run "./tests/realise-minimal-derivations"
run "./src/derivations-from-json.rb", "tests/nickel-derivation.json"
